  # -------------------------------------------------------------
  # Reverse Proxy (Zoraxy) â€“ Lightweight service
  # -------------------------------------------------------------
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    ports:
      - 80:80
      - 443:443
      - 8000:8000/tcp   # Admin interface
    volumes:
      - ./zoraxy/config:/opt/zoraxy/config/
      - ./zoraxy/plugin:/opt/zoraxy/plugin/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DOCKER: "true"
      MDNS: "false"
      TZ: "TZ=${TZ}"
    restart: unless-stopped
